import type { Metadata } from 'next';
import { Geist, Geist_Mono, Concert_One } from 'next/font/google';
import Providers from '@/components/providers';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const concertOne = Concert_One({
  variable: '--font-concert-one',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${concertOne.variable} antialiased dark`}
      >
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
